apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java
  namespace: sample-java
  labels:
    app: sample-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-java
  template:
    metadata:
      labels:
        app: sample-java
    spec:
      containers:
        - name: sample-java
          image: docker.io/krisdigitx/sample-java-maven-app:88ef486
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi